version: '2'

services:
  rabbitmq:
    image: rabbitmq:3-management
    networks:
      - mynetwork
    ports:
      - "5672:5672"
      - "15672:15672"
  eureka:
    image: hbanyal/eureka:v5
    restart: always
    networks:
      - mynetwork
    ports:
      - "8761:8761"
  search:
    image: hbanyal/search:v1
    restart: always
    networks:
      - mynetwork
    ports:
      - "8090:8090"
    links:
      - eureka
      - rabbitmq
  book:
    image: hbanyal/book:v1
    restart: always
    networks:
      - mynetwork
    ports:
      - "8091:8091"
    links:
      - eureka
      - rabbitmq 
  web:
    image: hbanyal/airweb:v1
    restart: always
    networks:
      - mynetwork
    ports:
      - "8001:8001"
    links:
      - eureka

    
  
  

  