version: '2'

services:

  eureka:
    image: hbanyal/eureka:v5
    restart: always
    ports:
      - "8761:8761"
  search:
    image: hbanyal/search:v1
    restart: always
    ports:
      - "8090:8090"
  book:
    image: hbanyal/book:v1
    restart: always
    ports:
      - "8091:8091"
  web:
    image: hbanyal/airweb:v1
    restart: always
    ports:
      - "8001:8001"
    
  
  

  