version: '2'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - eureka


  eureka:
    image: hbanyal/eureka:v5
    container_name: eureka
    restart: always
    networks:
      - eureka
    ports:
      - "8761:8761"

networks:
    eureka: