version: '2'

services:

  book:
    image: hbanyal/book:v1
    restart: always
    ports:
      - "8091:8091"
    external_links:
      - eureka
      - rabbitmq

networks:
    default:
        external:
           name: dockereureka_eureka
