version: '2'

services:

  search:
    image: hbanyal/search:v1
    container_name: search
    restart: always
    ports:
      - "8090:8090"
    external_links:
      - eureka

networks:
    default:
        external:
           name: eureka